"""Domain repository ports.

This module defines persistence contracts used by application services. Concrete
SQL implementations live under `crypto_predictor.infrastructure.persistence`.
"""

from __future__ import annotations

from typing import Any, Protocol

from crypto_predictor.broker.models import OrderResult
from crypto_predictor.models import MarketData, ModelType, Prediction

class PredictionRepository(Protocol):
    def init_schema(self) -> None: ...
    def save_prediction(self, market_data: MarketData, prediction: Prediction, model_type: ModelType) -> int: ...
    def count_predictions(self) -> int: ...
    def list_recent_predictions(self, limit: int = 50, offset: int = 0) -> list[Any]: ...
    def get_prediction_by_id(self, prediction_id: int | None) -> Any | None: ...
    def get_latest_prediction(self) -> Any | None: ...
    def get_latest_prediction_for_symbol(self, symbol: str) -> Any | None: ...
    def save_trade_order(self, prediction_id: int, result: OrderResult) -> int: ...
    def list_recent_trade_orders(self, limit: int = 50) -> list[Any]: ...
    def get_next_open_trade_order_expiry(self) -> str | None: ...
    def update_trade_order_close(self, order_id: int, payload: dict[str, object]) -> None: ...
    def get_next_pending_prediction_expiry(self) -> str | None: ...
    def list_expired_pending_predictions(self, now_iso: str) -> list[Any]: ...
    def update_prediction_accuracy(
        self,
        prediction_id: int,
        actual_price: float,
        is_accurate: bool,
        checked_at: str,
        validation_reason: str | None = None,
        validation_event_time: str | None = None,
    ) -> None: ...
    def list_expired_open_trade_orders(self, now_iso: str) -> list[Any]: ...
    def list_chart_predictions(
        self,
        symbol: str | None = None,
        limit: int = 100,
        start_utc: str | None = None,
        end_utc: str | None = None,
    ) -> list[Any]: ...
    def get_overall_accuracy(self) -> dict[str, object]: ...
    def save_auto_run_log(self, payload: dict[str, object]) -> int: ...
    def count_auto_run_logs(self) -> int: ...
    def list_recent_auto_run_logs(self, limit: int = 50, offset: int = 0) -> list[Any]: ...
    def get_auto_run_log_stats(self) -> dict[str, object]: ...
    def save_user_advice_action(self, payload: dict[str, object]) -> int: ...
    def list_recent_user_advice_actions(self, limit: int = 50) -> list[Any]: ...

